name: 'Jscrambler'
description: 'Protect your JavaScript Application with polymorphic obfuscation, code locks, and self-defensive techniques'
author: 'Jscrambler'
branding:
  icon: shield
  color: blue
runs:
  using: 'node16'
  main: 'main.js'
